# 工作流名称，会显示在 GitHub Actions 页面
name: Build and Push Multi-Platform Docker Image to GHCR

# 触发工作流的事件
on:
  # 当有代码推送到 main 分支时触发
  push:
    branches:
      - 'main'
  # 允许手动触发
  workflow_dispatch:

# 定义工作流中的任务
jobs:
  build-and-push:
    # 任务运行的环境
    runs-on: ubuntu-latest
    
    # 为此任务设置权限
    permissions:
      contents: read
      packages: write

    steps:
      # 第一步：检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 【新增步骤】设置 QEMU
      # QEMU 可以在 amd64 的构建机上模拟 arm64 等其他架构的环境，是实现跨平台构建的基础
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 第三步：设置 Docker Buildx
      # 这个步骤会创建一个支持多平台构建的 builder 实例
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 第四步：登录到 GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 第五步：提取 Docker 元数据
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: type=raw,value=latest

      # 第六步：构建并推送多平台镜像
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # 【关键修改点】指定要构建的平台
          # 这会同时构建 amd64 和 arm64 两种架构的镜像，并把它们关联到同一个 'latest' 标签下
          platforms: linux/amd64, linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # 缓存依然有效
          cache-from: type=gha
          cache-to: type=gha,mode=max
